# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        # -  Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        digits: 6
        enabled: true 
        sender_email: 'toto@toto.com'
        sender_name: 'toto airline'
        template: 'authentification/2fa_form.html.twig'
        # form_renderer: App\Form\TwoFactorType

