# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        # -  Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        digits: 6
        enabled: true 
        sender_email: 'toto@toto.com'
        sender_name: 'toto airline'
        template: 'authentification/2fa_form.html.twig'
        # form_renderer: App\Form\TwoFactorType
    trusted_device:
        enabled: true
        lifetime: 3600
        extend_lifetime: true
        cookie_name: trusted_divice
        cookie_secure: false
        cookie_same_site: "lax"
        cookie_domain: ".exemple.com"
        cookie_path: "/"

